### ISSUE TITLE
How to export vertex animation

### ISSUE THREAD

**Issue by liaocheng** [awaytools/AwayExtensions-3dsmax#21]
Hello
I failed to export the vertex animation. Here's my simple case: (3dsmax 2014)
http://www.effecthub.com/test/test.zip

I got this error:
Message: '- No keyframes read for animationclip. animationclip not exported'

Do you have a simple case ( a max file ) that can tell me how to do that?

Regards

**Comment by 80prozent** [comment]
hey 
I just had a look at your max file.
You get this error, because the vertices of the mesh are not animated. 
The local position of the vertices are not changing between the keyframes.
To have this animation exported as vertex-animation, all you need to change is the Transform-property of the animation-clip in the clip-manager. this will tell the exporter to bake the matrix-animation of the mesh into vertex-animation.
http://www.differentdesign.de/downloads/max_screen.jpg

I just tested, and this way, the animation gets exported for me.

Hope this is of any help.

**Comment by liaocheng** [comment]
Thank you very much. It works for me too!
